### ISSUE TITLE
Ubuntu 18.04.6 LTS 的docker中运行全部规则都是空

### ISSUE THREAD

**Issue by jcleng** [pretty66/iptables-web#10]

**Comment by pretty66** [comment]
docker运行有没有加这两个参数，--privileged=true --net=host

**Comment by jcleng** [comment]
> docker运行有没有加这两个参数，--privileged=true --net=host

加上的

**Comment by pretty66** [comment]
> > docker运行有没有加这两个参数，--privileged=true --net=host
> 
> 加上的

检查下docker的network，参考这个文档：
[network](https://blog.51cto.com/u_16213382/7451505)
