### ISSUE TITLE
按照教程部署好了,web页面也能打开,但是不展示任何规则,看docker日志也是空的

### ISSUE THREAD

**Issue by chenb1522** [pretty66/iptables-web#6]
按照教程部署好了,web页面也能打开,但是不展示任何规则,看docker日志也是空的

**Comment by yaf0** [comment]
这。。你部署在容器里的？

**Comment by chenb1522** [comment]
> 我使用是正常的，没有用docker，如果本身没有任何规则，那打开之后规则就应该是空的

真相了,在docker里确实无法访问宿主机的iptables信息,即使我加了 '--net=host' 也没生效, 可能跟我的linux发行版本和docker版本不有关系. linux版本:Linux version 3.10.0-1160.71.1.el7.x86_64, docker版本:23.0.1

**Comment by huapox** [comment]
+1, 宿主机内是可用的
