### ISSUE TITLE
ipset支持+去掉登录接口

### ISSUE THREAD

**Issue by pan2za** [pretty66/iptables-web#7]
1 是否可以加上ipset支持
2 是否能去掉登录接口，方便集成到别的地方

**Comment by pretty66** [comment]
1.暂时不打算支持
2.如果需要集成的话很简单，这个登录用的是Authorization Basic认证；在对接时加个请求头就行了

**Comment by pretty66** [comment]
1.不知道具体需求是什么样的，如果有详细的需求文档可以考虑；另外非常欢迎您这边能提pr
2.如果需要集成的话很简单，这个登录用的是Authorization Basic认证；在对接时加个请求头就行了
