### ISSUE TITLE
参考easywall的几个建议，这个我们在改

### ISSUE THREAD

**Issue by pan2za** [pretty66/iptables-web#8]
![cd4e91c2bc62b5706eaf763a1d71dfd](https://github.com/pretty66/iptables-web/assets/10153561/891ca448-f7e8-47f7-a215-bdcc1aa8b290)

**Comment by pan2za** [comment]
![iptables商用化](https://github.com/pretty66/iptables-web/assets/10153561/30d5a1b2-cf5e-400a-aa33-81e655a99808)

**Comment by pretty66** [comment]
需求合理的话，可以提个pr👍🏻
